### ISSUE TITLE
Single file and associated type of expected extract

### ISSUE THREAD

**Issue by Mokhet** [dcmc87/MFFRosterParserWeb#3]
Instead of sending multiple files, I would like to send one single screenshot and the type of extract I expect from it.

Fields could be :

1) "file" : The file sended (base64 encoded, raw or any other format that best suit your needs)
2) "type" : The type of extract. We could use numeric code or string code. I have a preference for string code because as a human I remember better what it means :)

**Comment by dcmc87** [comment]
Raw format should be fine for the image. And string code is fine too.

However, I can currently auto-detect the type of extract (gear/details) from the image, I could actually just send a type field back to you instead?

**Comment by Mokhet** [comment]
if auto-detection is easy on your side, getting the type field back in the JSON response would be great.

**Comment by dcmc87** [comment]
I'm currently configured to accept files in a FormData object, is that the way you'd usually do it, or is there another way to post the files?

**Comment by Mokhet** [comment]
I think FormData object is ok. It is the same as the old form way, but from the browser.
<form enctype="multipart/form-data" method="post">
  <input type="file" name="file">
  <input type="submit">
</form>

However I think will not call your API from the browser but from my server, dunno really yetI will know more in a moment when I will start coding the whole thing. First to prevent any CORS issue and also to be able to apply more image detection, for instance I think I will extract URU from the image after submitting it to your API if it is a success and a "gear" type.

For now the workflow I imagine is :

1) user add screenshots
2) async send to my server all images
3) sync send to your server images one by one
3.a) if "detail" type, send back to browser
3.b) if "gear" type, do URU extract and send back to browser
4) show results to user until all async calls are completed, and let him make some changes in case of errors in the detection (kind of confirm to the data)
5) wait until user has validated each images extract and add it to the local data

**Comment by dcmc87** [comment]
Sounds fine, just a few thoughts :

1. I'm not familiar with php, but if you could multiprocess on the server
you could send multiple images to my api individually but simultaneously.

It'd probably be more efficient to send them grouped together, but it would
 probably a pain to figure out which response went with which image

2. In terms of CORS there should be no issue, I've added your domain and
also tested with a separate domain of mine. If you send files from your
server I think my current way of retrieving files should work if the param
is still set to 'file'

3. By the way, out of curiosity how do you plan to extract the uru? If it's
simple enough I could just process that as well so you don't have to route
it through your server as well

Ps there might be a bit of hiccup with my API over the next day or so, I'm
experimenting with migrating to a different VPS and using nginx as well


On 16 Apr 2017 21:53, "Laurent Vilday" <notifications@github.com> wrote:

I think FormData object is ok. It is the same as the old form way, but from
the browser.

However I think will not call your API from the browser but from my server,
dunno really yetI will know more in a moment when I will start coding the
whole thing. First to prevent any CORS issue and also to be able to apply
more image detection, for instance I think I will extract URU from the
image after submitting it to your API if it is a success and a "gear" type.

For now the workflow I imagine is :

   1. user add screenshots
   2. async send to my server all images
   3. sync send to your server images one by one
   3.a) if "detail" type, send back to browser
   3.b) if "gear" type, do URU extract and send back to browser
   4. show results to user until all async calls are completed, and let him
   make some changes in case of errors in the detection (kind of confirm to
   the data)
   5. wait until user has validated each images extract and add it to the
   local data

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/dcmc87/MFFRosterParserWeb/issues/3#issuecomment-294352940>,
or mute the thread

**Comment by Mokhet** [comment]
I am afraid of timeout issues if I send grouped files. If we go the grouped way, I would need the file name or an id I would have provided to your API in the response so I can correctly map answers to files.

I have no idea yet how to extract uru from the images. Probably resizing the image to a specific size and check some specifics pixels colours to find out the kind of uru and the levels. I don't even know if I am able to do such kind of thing :) If you can do the uru extraction that's would be great, in this case I would of course directly call your server from the tool instead of the cumbersome way from mine to yours.

**Comment by dcmc87** [comment]
Yeah I think single files are a lot less trouble for everyone even though
it might take a little longer, but as I said you can try sending them in
parallel.

As for the uru yeah it's pretty easy for me to do pixel and color matching
although I was hoping you had some other brilliant idea lol. I'll see if I
can get it reasonably accurate but probably will take a while because I
have to calculate the pixels and color averages for all the uru and stars
lol

**Comment by Mokhet** [comment]
Yes, I too think single files are less trouble. And yes, I am currently coding it in a parallel way with async calls.

You convinced me to give up on uru extract on my own :) But don't worry, no rush especially with the incoming MFF 3.0 UI redesign. And uru tracking is not planned for the current release 2.4 yet, it is way behind gear tracking which already give me headaches :)

**Comment by dcmc87** [comment]
Yeah I'll hold off on the uru till 3.0 then, no point having to redo
everything next week
